name: Dev_build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest

      - name: Wrapper Validation
        uses: gradle/actions/wrapper-validation@latest

      - name: Setup JDK 25
        uses: actions/setup-java@latest
        with:
          java-version: 25
          distribution: temurin

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get Versions
        run: |
          MC_VERSION=$(./gradlew -q printMCVersion)
          PROJECT_VERSION=$(./gradlew -q printVersion)

          echo "MC_VERSION=$MC_VERSION" >> $GITHUB_ENV
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
      
      - name: Archive Artifacts
        uses: actions/upload-artifact@latest
        with:
          name: Artifacts
          path: build/libs/*.jar

      # - name: Create Build release
      #   uses: marvinpinto/action-automatic-releases@latest
      #   with:
      #     repo_token: '${{ secrets.GITHUB_TOKEN }}'
      #     automatic_release_tag: "${{ env.MC_VERSION }}-${{ env.PROJECT_VERSION }}"
      #     prerelease: true
      #     title: "Version ${{ env.PROJECT_VERSION }} for Minecraft ${{ env.MC_VERSION }}"
      #     files: |
      #       ./build/libs/*.jar
